### ISSUE TITLE
unable to convert

### ISSUE THREAD

**Issue by Blublu6** [barsgroup/plsql-postgresql-converter#3]
Hello,

I try to convert a simple request from a texte file, but always get this message:

"line 1:0 missing EOF at 'select'
Parse took 0,646000 seconds"

The resquest : select * from dual; (in utf-8 or ansi txt file)
The command: java -jar plsqlconverter.jar --tree-type sql_script --input-sql sql2.txt --output-sql - --convert --use-pgsql

Executed from windows 10.

Regards

Blublu6

**Comment by dmitryvk** [comment]
Hi,

`--tree-type sql_script` is for SQL DDL scripts that contain many SQL statements like `create table`.

If you use `--tree-type sql_statement` then you would get converted result:

```
$ java -jar plsqlconverter.jar --tree-type sql_statement --input-sql sql2.txt --output-sql - --convert --use-pgsql
Parse took 0.532000 seconds
doing nested functions...
doing procedure to function...
doing misc conversion...
doing outer joins...
doing packages...
doing datatypes...
doing perform...
select *


```

**Comment by Blublu6** [comment]
Hi!

Works much better! 

Thank you for your awesome work!

Regards,

BB6
